# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fn8_oiNjuA6kvodYw2QP1blbwdKlqDXP
"""

import streamlit as st
import tensorflow as tf
import numpy as np
import cv2
from PIL import Image
import io

MODEL_PATH = 'facial_emotion_cnn_model_FAST.h5'
CASCADE_PATH = 'haarcascade_frontalface_default.xml'
IMG_SIZE = 48
EMOTIONS = ['Angry', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']

st.set_page_config(
    page_title="Facial Emotion Recognition App",
    layout="centered",
    initial_sidebar_state="collapsed"
)

@st.cache_resource
def load_resources():
    """Loads the pre-trained Keras model and Haar Cascade classifier once."""
    try:
        tf.get_logger().setLevel('ERROR')
        model = tf.keras.models.load_model(MODEL_PATH, compile=False)
        face_cascade = cv2.CascadeClassifier(CASCADE_PATH)

        if face_cascade.empty():
             st.error("Error: Face detector failed to load.")
             return None, None

        return model, face_cascade
    except Exception as e:
        st.error(f"Failed to load AI Model: {e}")
        st.warning(f"Please check if {MODEL_PATH} is present in the GitHub repository.")
        return None, None

model, face_cascade = load_resources()

def predict_emotion(image, model, face_cascade):
    """Detects faces, predicts emotion, and draws bounding boxes/text."""

    img_array = np.array(image.convert('RGB'))
    gray_img = cv2.cvtColor(img_array, cv2.COLOR_RGB2GRAY)

    faces = face_cascade.detectMultiScale(
        gray_img, scaleFactor=1.1, minNeighbors=5, minSize=(30, 30)
    )

    if len(faces) == 0:
        return img_array, 0

    for (x, y, w, h) in faces:
        roi_gray = gray_img[y:y + h, x:x + w]
        cropped_img = cv2.resize(roi_gray, (IMG_SIZE, IMG_SIZE))

        cropped_img = cropped_img.astype('float32') / 255.0
        processed_input = np.expand_dims(cropped_img, axis=(0, 3)) # (1, 48, 48, 1)

        predictions = model.predict(processed_input, verbose=0)[0]
        emotion_index = np.argmax(predictions)
        emotion_label = EMOTIONS[emotion_index]
        confidence = predictions[emotion_index] * 100

        color = (0, 255, 0)

        cv2.rectangle(img_array, (x, y), (x + w, y + h), color, 2)

        text = f"{emotion_label}: {confidence:.1f}%"
        cv2.putText(img_array, text, (x, y - 10),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2, cv2.LINE_AA)

    return img_array, len(faces)

def main():
    st.title("🧠 Facial Expression Recognizer (FER-2013)")
    st.markdown("### B.Tech AI/DL Project Demonstration")
    st.write("---")

    if model is None:
        st.stop()

    st.info("**Instructions:** Upload an image with faces to see the model's prediction.")

    uploaded_file = st.file_uploader(
        "Upload an image file (.jpg, .jpeg, .png)",
        type=["jpg", "jpeg", "png"]
    )

    if uploaded_file is not None:
        try:
            image = Image.open(uploaded_file)

            col1, col2 = st.columns(2)

            with col1:
                st.markdown("**Uploaded Image**")
                st.image(image, use_column_width=True)

            if st.button('Analyze Emotion', use_container_width=True):
                with st.spinner('Analyzing faces and predicting emotions...'):
                    result_img_array, face_count = predict_emotion(image, model, face_cascade)

                result_img = Image.fromarray(result_img_array)

                with col2:
                    st.markdown("**Emotion Analysis**")
                    if face_count > 0:
                        st.image(result_img, caption=f'Detected {face_count} face(s)', use_column_width=True)
                        st.success("Analysis Complete!")
                    else:
                        st.warning("No faces detected in the image.")
                        st.image(image, use_column_width=True)

        except Exception as e:
            st.exception(e)
            st.error("An unexpected error occurred during processing.")

if __name__ == "__main__":
    main()